version: '2'

services:
  apache:
    build: ./docker/build/apache/
    links:
      - mysql
      - postfix
    ports:
      - "80:80"
    volumes:
      - ./docker/etc/apache/kwo.conf:/etc/apache2/sites-enabled/default.conf
      - ./docker/etc/php/php.ini:/etc/php/php.ini
      - ./docker/etc/php/php-cli.ini:/etc/php/php-cli.ini
      - ./app/kwo:/var/web/app
      - ./log/apache:/var/log/apache2
  
  mysql:
    image: mysql:5.6
    ports:
      - "3306"
    volumes:
      - ./docker/etc/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - /var/lib/mysql/
      - ./data:/data
    environment:
      MYSQL_ROOT_PASSWORD: azerty
      MYSQL_DATABASE: test

  phpmyadmin:
    image: nazarpc/phpmyadmin
    links:
      - mysql
    ports:
      - "8001:80"

  postfix:
    image: catatnight/postfix
    ports:
      - "25"
    environment:
      maildomain: "mail.local"
      smtp_user: sender:azerty
