<?php 

$ctx->chars = array('euro', 'pound', 'cent', 'yen', 'trade', 'copy', 'reg',
                    'permil', 'infin', 'divide', 'plusmn', 
                    'le', 'ge', 'asymp', 'ne', 'equiv', 'sum', 'radic',
                    'sup1', 'sup2', 'sup3','frac12', 'frac14', 'frac34', 
                    'middot', 'bull', 
                    'laquo', 'raquo', 'lsaquo', 'rsaquo',
                    'ldquo', 'rdquo', 'lsquo', 'rsquo', 'mdash', 'ndash', 'hellip',
                    'apos', 'larr', 'uarr', 'rarr', 'darr', 'harr', 'times',
                    'oelig', 'circ', 'tilde', 'para', 'iquest', 'dagger', 'curren', 'brvbar',
                    'loz', 'clubs', 'hearts', 'diams');

$res->useTemplate();
